### ISSUE TITLE
character argument expected

### ISSUE THREAD

**Issue by helix123** [MangoTheCat/rcmdcheck#14]
Running 1.0 I get:

    rcmdcheck(getwd())
    Error in setwd(dir = new) : character argument expected
    Called from: setwd(dir = new)

working dir is set to the package...

**Comment by gaborcsardi** [comment]
What OS? What package? Can you provide a reproducible example?

**Comment by pitakakariki** [comment]
I got the same error, just after I installed R version 3.3.0. Tried `devtools::check` instead, which told me there were packages I needed to install.

Once I installed `roxygen2` and `rmarkdown` (and their dependencies) `rcmdcheck` worked fine.

**Comment by gaborcsardi** [comment]
`rcmdcheck` does not need `roxygen2` or `rmarkdown`, and it should start the check even if your dependencies are not installed.

I think this error happens if the working directory is not the package root. E.g. 
```r
❯ getwd()
[1] "/Users/gaborcsardi/works/parr/R"

✔ 51.5 MiB master*
❯ rcmdcheck(getwd())
Error in setwd(dir = new) : character argument expected

✖ 51.5 MiB master*
❯ setwd("..")

✔ 51.5 MiB master*
❯ rcmdcheck(getwd())
────────────────────────────────────────────────────────────────────────────────
─  using log directory ‘/private/var/folders/ws/7rmdm_cn2pd8l1c3lqyycv0c0000gn/T/Rtmpu22v1m/filef53c185a430/parr.Rcheck’
─  using R version 3.2.4 (2016-03-10)
─  using platform: x86_64-apple-darwin13.4.0 (64-bit)
─  using session charset: UTF-8
✔  checking for file ‘parr/DESCRIPTION’
─  this is package ‘parr’ version ‘3.3.0’
✔  checking package namespace information
...
```

**Comment by pitakakariki** [comment]
I was in the package root. In my case it's whether or not `knitr` is installed. My package suggests `knitr`  for its vignettes.

    > rcmdcheck::rcmdcheck()
    Error in setwd(dir = new) : character argument expected > 

    > install.packages("knitr")
    package ‘knitr’ successfully unpacked and MD5 sums checked

    > rcmdcheck::rcmdcheck()
    ...
    0 errors ✔ | 0 warnings ✔ | 0 notes ✔

It seems to break down when the package fails to build:

    > remove.packages("knitr")
    > rcmdcheck:::build_package(".")
    character(0)

So it's trying to set the working directory based on a zero-length character vector. You might want to print the build output to the console, or maybe capture it and print it if the build fails?

    > system("R CMD build .")
    * checking for file './DESCRIPTION' ... OK
    * preparing 'simr':
    * checking DESCRIPTION meta-information ... OK
    Error in loadVignetteBuilder(pkgdir, TRUE) : 
      vignette builder 'knitr' not found
    Execution halted
    Warning message:
    running command 'R CMD build .' had status 1

**Comment by gaborcsardi** [comment]
Oh, got it. The build phase fails already. Makes sense. I need to install the `VignetteBuilder`before even building the package.

**Comment by gaborcsardi** [comment]
So I suppose it could give an error message when the `build` step fails.
